import test,{mock} from 'node:test';
import assert from 'node:assert/strict';
import './register-paths.mjs';
let records,accounts,creates;
const clone=v=>structuredClone(v);
function snap(path) {return {id:path.split('/').at(-1),ref:ref(path),exists:records.has(path),data:()=>records.has(path)?clone(records.get(path)):undefined};}
function ref(path,filters=[],take=Infinity,cursor=null) {
 const doc=path.split('/').length%2===0;
 const get=async()=>{if(doc)return snap(path);const docs=[...records.keys()].filter(k=>k.startsWith(path+'/')&&k.split('/').length===path.split('/').length+1).sort().filter(k=>filters.every(([f,v])=>records.get(k)[f]===v)).filter(k=>!cursor||k.split('/').at(-1)>cursor).slice(0,take).map(snap);return {docs};};
 return {path,id:path.split('/').at(-1),collection:n=>ref(path+'/'+n),doc:id=>ref(path+'/'+(id||crypto.randomUUID())),get,where:(f,op,v)=>{assert.equal(op,'==');return ref(path,[...filters,[f,v]],take,cursor);},limit:n=>ref(path,filters,n,cursor),orderBy:()=>ref(path,filters,take,cursor),startAfter:s=>ref(path,filters,take,s.id),count:()=>({get:async()=>{const {docs}=await get();return {data:()=>({count:docs.length})};}})};
}
function write(path,data,merge=false) {
 const old=records.get(path)||{},value=merge?{...old}:{};
 for(const [k,v]of Object.entries(data)) value[k]=v?.methodName==='FieldValue.serverTimestamp'?new Date().toISOString():v?.methodName==='FieldValue.increment'?(Number(old[k])||0)+v.operand:clone(v);
 records.set(path,value);
}
const db={collection:n=>ref(n),runTransaction:async fn=>{const writes=[];const result=await fn({get:r=>r.get(),set:(r,d,o)=>writes.push(()=>write(r.path,d,o?.merge)),update:(r,d)=>writes.push(()=>write(r.path,d,true))});writes.forEach(w=>w());return result;}};
const auth={verifyIdToken:async token=>{if(!['admin','admin2','student','teacher','suspended'].includes(token))throw Error('invalid');return {uid:token};},getUserByEmail:async email=>{const user=accounts.get(email);if(!user)throw Object.assign(Error('not-found'),{code:'auth/user-not-found'});return user;},createUser:async input=>{creates++;const user={...input,uid:'created-'+creates,disabled:false};accounts.set(input.email,user);return user;}};
mock.module('../src/lib/firebase/admin.ts',{namedExports:{getAdminDb:()=>db,getAdminAuth:()=>auth}});
const api=await import('../src/app/api/admin/route.ts');
const service=await import('../src/lib/server/admin-service.ts');
const {adminCsv}=await import('../src/lib/admin/csv.ts');
const {consumeAiUsage}=await import('../src/lib/server/ai-usage.ts');
function setup(){records=new Map([
 ['users/admin',{name:'Admin',role:'admin',status:'active'}],['users/admin2',{name:'Otro',role:'admin',status:'active'}],['users/teacher',{name:'Docente',role:'teacher',status:'active'}],['users/teacher2',{name:'Docente 2',role:'teacher',status:'active'}],['users/student',{name:'Estudiante',email:'student@test.example',role:'student',status:'active'}],['users/suspended',{role:'admin',status:'suspended'}],
 ['courses/course1',{teacherId:'teacher',name:'Materia',code:'MAT',period:'2026',status:'active',sectionsCount:1,studentsCount:0}],['sections/section1',{teacherId:'teacher',courseId:'course1',code:'A',capacity:2,status:'active'}],['sections/foreign',{teacherId:'teacher2',courseId:'foreign',capacity:2,status:'active'}],
 ['assessments/assessment1',{teacherId:'teacher',courseId:'course1',sectionId:'section1',title:'Examen',maxScore:20,weightPercentage:30,status:'open'}],
 ]);accounts=new Map([['existing@test.example',{uid:'existing',email:'existing@test.example',disabled:false}]]);creates=0;}
const request=(data,token='admin')=>new Request('http://localhost/api/admin',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:JSON.stringify(data)});
const save=(resource,data,id=null,token='admin')=>api.POST(request({action:'save',resource,id,data,reason:'Cambio académico autorizado'},token));
const enrollment={courseId:'course1',sectionId:'section1',studentId:'student',status:'active'};

test('admin API: todos los endpoints bloquean anónimos, docentes, estudiantes y suspendidos',async()=>{setup();for(const token of ['', 'bad','student','teacher','suspended']){const get=await api.GET(new Request('http://localhost/api/admin?resource=users',{headers:{Authorization:`Bearer ${token}`}}));assert.equal(get.status,['','bad'].includes(token)?401:403);assert.equal((await save('users',{name:'Admin',role:'admin',status:'active'},'admin',token)).status,['','bad'].includes(token)?401:403);}assert.equal((await api.GET(new Request('http://localhost/api/admin?resource=users',{headers:{Authorization:'Bearer admin'}}))).status,200);});
test('admin API: rechaza JSON, rutas, campos sensibles y motivo insuficiente sin escribir',async()=>{setup();const size=records.size;assert.equal((await api.POST(new Request('http://localhost/api/admin',{method:'POST',headers:{Authorization:'Bearer admin'},body:'{'}))).status,400);assert.equal((await save('users',{name:'Prueba',role:'student',status:'active'},'a/b')).status,400);assert.equal((await save('users',{name:'Prueba',role:'student',status:'active',password:'secret'},'student')).status,400);assert.equal((await api.POST(request({action:'save',resource:'users',id:'student',data:{},reason:'x'}))).status,400);assert.equal(records.size,size);});
test('admin: protege la propia cuenta y roles con materias o matrículas',async()=>{setup();assert.equal((await save('users',{name:'Admin',role:'student',status:'active'},'admin')).status,409);assert.equal((await save('users',{name:'Docente',role:'student',status:'active'},'teacher')).status,409);await save('enrollments',enrollment);assert.equal((await save('users',{name:'Estudiante',role:'teacher',status:'active'},'student')).status,409);assert.equal(records.get('users/admin').role,'admin');assert.equal((await save('users',{name:'Otro',role:'student',status:'active'},'admin2')).status,200);});
test('admin: crea o vincula Auth sin contraseñas ni cambios en la cuenta existente',async()=>{setup();let response=await api.POST(request({action:'create-user',email:'existing@test.example',name:'Nuevo docente',role:'teacher',reason:'Registro nuevo docente'}));assert.equal(response.status,201);assert.equal(creates,0);assert.equal(records.get('users/existing').role,'teacher');assert.equal(accounts.get('existing@test.example').displayName,undefined);response=await api.POST(request({action:'create-user',email:'existing@test.example',name:'Otro',role:'admin',reason:'Intento de duplicación'}));assert.equal(response.status,409);assert.equal(records.get('users/existing').role,'teacher');response=await api.POST(request({action:'create-user',email:'new@test.example',name:'Estudiante nuevo',role:'student',reason:'Registro de estudiante'}));assert.equal(response.status,201);assert.equal(creates,1);assert.ok(!('password' in accounts.get('new@test.example')));});
test('admin: matrícula valida sección, capacidad, estado y contadores idempotentes',async()=>{setup();assert.equal((await save('enrollments',{...enrollment,sectionId:'foreign'})).status,409);assert.equal((await save('enrollments',enrollment)).status,200);assert.equal(records.get('courses/course1').studentsCount,1);assert.equal((await save('enrollments',enrollment,'course1--student')).status,200);assert.equal(records.get('courses/course1').studentsCount,1);assert.equal((await save('enrollments',{...enrollment,status:'inactive'},'course1--student')).status,200);assert.equal(records.get('courses/course1').studentsCount,0);records.get('sections/section1').capacity=1;records.set('enrollments/other',{sectionId:'section1',status:'active'});assert.equal((await save('enrollments',enrollment,'course1--student')).status,409);});
test('admin: transferir materia actualiza todos los responsables en una transacción y audita motivo',async()=>{setup();await save('enrollments',enrollment);for(const c of ['lessonPlans','materials','onlineClasses','grades','attendance'])records.set(c+'/item',{teacherId:'teacher',courseId:'course1'});const r=await save('courses',{teacherId:'teacher2',name:'Materia',code:'MAT',period:'2026',status:'active'},'course1');assert.equal(r.status,200);for(const [path,d]of records)if(d.courseId==='course1'||path==='courses/course1')assert.equal(d.teacherId,'teacher2',path);const audits=[...records.entries()].filter(([k])=>k.startsWith('adminAudit/'));assert.equal(audits.length,2);assert.equal(audits.at(-1)[1].actorId,'admin');assert.equal(audits.at(-1)[1].reason,'Cambio académico autorizado');});
test('admin: transferencia con más de 400 dependencias no modifica nada',async()=>{setup();for(let i=0;i<401;i++)records.set('materials/'+i,{teacherId:'teacher',courseId:'course1'});assert.equal((await save('courses',{teacherId:'teacher2',name:'Materia',code:'MAT',period:'2026',status:'active'},'course1')).status,409);assert.equal(records.get('courses/course1').teacherId,'teacher');assert.equal([...records.keys()].filter(k=>k.startsWith('adminAudit/')).length,0);});
test('admin: nota deriva escala, ponderación y sección; rechaza puntos y evaluación ajena',async()=>{setup();await save('enrollments',enrollment);const data={courseId:'course1',studentId:'student',assessmentId:'assessment1',score:16,status:'published',feedback:'Bien'};assert.equal((await save('grades',{...data,score:21})).status,400);assert.equal((await save('grades',data)).status,200);const grade=records.get('grades/assessment1--student');assert.equal(grade.maxScore,20);assert.equal(grade.normalizedPercentage,80);assert.equal(grade.weightedPoints,24);assert.equal(grade.sectionId,'section1');records.get('assessments/assessment1').sectionId='foreign';assert.equal((await save('grades',data,'assessment1--student')).status,409);});
test('admin: rúbrica excedida y sección ajena no se publican; notas bloquean cambio de escala',async()=>{setup();const data={courseId:'course1',sectionId:'section1',title:'Evaluación',type:'exam',deliveryMode:'manual',weightPercentage:30,maxScore:20,passingScore:10,status:'open',rubric:[{id:'r1',title:'Criterio',points:21}]};assert.equal((await save('assessments',data)).status,400);assert.equal((await save('assessments',{...data,rubric:[],sectionId:'foreign'})).status,409);records.set('grades/g',{assessmentId:'assessment1'});assert.equal((await save('assessments',{...data,rubric:[],maxScore:25},'assessment1')).status,409);assert.equal(records.get('assessments/assessment1').maxScore,20);});
test('admin: asistencia exige matrícula activa y fecha válida; no altera identidades',async()=>{setup();const data={courseId:'course1',studentId:'student',date:'2026-10-07',status:'present'};assert.equal((await save('attendance',data)).status,404);await save('enrollments',enrollment);assert.equal((await save('attendance',{...data,date:'2026-02-30'})).status,400);assert.equal((await save('attendance',data)).status,200);const [path]=[...records.keys()].filter(k=>k.startsWith('attendance/'));assert.equal((await save('attendance',{...data,date:'2026-10-08'},path.split('/')[1])).status,409);});
test('admin: configuración aplica cupo a solicitudes reales y rechaza secretos',async()=>{setup();const data={institutionName:'Instituto',academicPeriod:'2026',dailyAiLimit:1,announcement:'Aviso'};assert.equal((await save('settings',{...data,LOCAL_AI_TOKEN:'secret'})).status,400);assert.equal((await save('settings',data,'general')).status,200);assert.equal((await consumeAiUsage('student')).allowed,true);assert.equal((await consumeAiUsage('student')).allowed,false);assert.equal(records.get('systemSettings/general').dailyAiLimit,1);});
test('admin: paginación no omite ni repite y reporte usa solo notas publicadas',async()=>{setup();for(let i=0;i<55;i++)records.set('materials/id-'+String(i).padStart(2,'0'),{title:'Guía'});const a=await service.adminList('materials');assert.equal(a.records.length,50);const b=await service.adminList('materials',a.nextCursor);assert.equal(b.records.length,5);assert.equal(new Set([...a.records,...b.records].map(r=>r.id)).size,55);records.set('grades/published',{courseId:'course1',status:'published',score:16,maxScore:20});records.set('grades/draft',{courseId:'course1',status:'draft',score:0,maxScore:20});const report=await service.adminReport();assert.equal(report.records[0].averagePercentage,80);assert.equal(report.records[0].publishedGrades,1);});
test('admin: exportación CSV conserva comillas y neutraliza fórmulas',()=>{const csv=adminCsv([{name:'=HYPERLINK("evil")',note:'línea; "dos"',count:10}]);assert.ok(csv.startsWith('\uFEFF'));assert.ok(csv.includes("'=HYPERLINK"));assert.ok(csv.includes('""dos""'));});
test('integración docente: crear y reactivar matrículas respeta la capacidad del administrador',async()=>{
 setup();const {createTeacherEnrollment,updateTeacherEnrollment}=await import('../src/lib/server/teacher-enrollment-admin.ts');
 records.get('sections/section1').capacity=1;records.set('enrollments/occupied',{sectionId:'section1',status:'active'});
 await assert.rejects(createTeacherEnrollment('teacher',enrollment),e=>e.code==='enrollment/full-section');
 records.delete('enrollments/occupied');await createTeacherEnrollment('teacher',enrollment);
 assert.equal(records.get('courses/course1').studentsCount,1);
 await updateTeacherEnrollment('teacher',{enrollmentId:'course1--student',status:'inactive'});
 records.set('enrollments/occupied',{sectionId:'section1',status:'active'});
 await assert.rejects(updateTeacherEnrollment('teacher',{enrollmentId:'course1--student',status:'active'}),e=>e.code==='enrollment/full-section');
});
test('admin: registrar asistencia repetida actualiza el documento utilizado por el docente',async()=>{
 setup();await save('enrollments',enrollment);
 const data={courseId:'course1',studentId:'student',date:'2026-10-07',status:'present'};
 assert.equal((await save('attendance',data)).status,200);assert.equal((await save('attendance',{...data,status:'late'})).status,200);
 const rows=[...records.entries()].filter(([key])=>key.startsWith('attendance/'));assert.equal(rows.length,1);assert.equal(rows[0][0],'attendance/course1--section1--2026-10-07--student');assert.equal(rows[0][1].status,'late');const audits=[...records.values()].filter(r=>r.resource==='attendance');assert.equal(audits.at(-1).after.createdAt,rows[0][1].createdAt);
});
